language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --no-suggest --dev

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
 -  vendor/bin/php-coveralls -v
